### ISSUE TITLE
Named graph support

### ISSUE THREAD

**Issue by maurert** [coronabytes/dotnet-arangodb#16]
I'm looking for a .net core compatible implementation of the arangodb graph api. As described here:
https://www.arangodb.com/docs/stable/http/gharial.html

It looks like this repository does not support most named graph operations? Yet?

**Comment by coronabytes** [comment]
yeah, no gharial api (https://www.arangodb.com/docs/stable/http/gharial-management.html) except graph list / create / drop,
For our projects regular direct edge collection modification is enough.

I'd like the add the api, however right now there is just no time, but pull requests are welcome ;-p
and as long as the unit tests run they would be merged and published rather fast

**Comment by coronabytes** [comment]
@maurert 
Hi, can you please look at https://github.com/coronabytes/dotnet-arangodb/blob/gharial/Core.Arango.Tests/GraphTest.cs
would this be enough? returOld returnNew,... not yet bound

**Comment by coronabytes** [comment]
released in 3.1
