### ISSUE TITLE
Secure ArangoHttpTransport request

### ISSUE THREAD

**Issue by sakisk** [coronabytes/dotnet-arangodb#20]
Is there a way currently supported to setup [ArangoHttpTransport](https://github.com/coronabytes/dotnet-arangodb/blob/master/Core.Arango/Transport/ArangoHttpTransport.cs) to send secure requests to arangodb server? I could implement my own `IArangoHttpTransport` but would be nice if [HttpClient](https://github.com/coronabytes/dotnet-arangodb/blob/65946ea3a2fa24be98188bf8e0294e3717580c47/Core.Arango/Transport/ArangoHttpTransport.cs#L22) was injected via the constructor instead of instantiated internally to this class and registering either to pass in a client configured with proper certificates or maybe register the ArangoHttpTransport as a [typed/named http client](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Comment by coronabytes** [comment]
Server=https://... should just work (with trusted certificates)

however ill add an constructor where one can set the default HttpClient / Handler
