### ISSUE TITLE
How to create a persistent index

### ISSUE THREAD

**Issue by isaacfi** [coronabytes/dotnet-arangodb#25]
Hi,

¿What is the equivalent or how to create a persistent index?

The Index types are:

Edge
FullText
Geo
Hash
Primary
Skiplist
Ttl

BR

**Comment by coronabytes** [comment]
in older arangodb docs they claimed it was deprecated and you should use Hash or Skiplist.
being the only option in the web interface I believe this was a misunderstanding.

I'll add it back in again

**Comment by coronabytes** [comment]
fixed in 3.8.211
