### ISSUE TITLE
cancellationToken on LINQ Query?

### ISSUE THREAD

**Issue by Mrjuanblack** [coronabytes/dotnet-arangodb#34]
Hello,

I've been using your driver for some days. I'm not that proficient on working with other people's code, so I might have overlooked some things around.

I have a case where I want to get a list of all of the entities (or documents) inside a collection, so I'm using LINQ Queries for that, as I find it quite easy to use it. The problem is that I cant seem to find where I can pass the cancellation token that you ussually find inside other Async methods.

For example

`var q = arango.Query<AnotherTestPerson>("TestDB").FirstAsync();`

Any help with that would be appreciated.

Thanks!

**Comment by coronabytes** [comment]
Added in 3.8.410 for consistency sake
