### ISSUE TITLE
Next NuGet Release

### ISSUE THREAD

**Issue by Snotax** [coronabytes/dotnet-arangodb#42]
When is your next release going to be available as a NuGet package ?

You guys fixed my error / request last friday extremly fast and I'm greatful, but it would be nice to know when it's going to be available.

Thanks for your help, keep up the good work.

**Comment by coronabytes** [comment]
I'll prepare the 3.9.0 package tonight,
Just a bit busy with multiple datacenters failing in europe at the syme time (azure devops, scaleway, ...)
