### ISSUE TITLE
LINQ Query Document Delete

### ISSUE THREAD

**Issue by Snotax** [coronabytes/dotnet-arangodb#45]
Hi, I just wanted to ask if deleting a document with LINQ is possible. I didn't find anything in the documentation or the tests.

Something like: .Where(t => t.Key== "").DeleteAsync() 

Thanks for your help!

**Comment by coronabytes** [comment]
```csharp
await Arango.Query<Project>("test")
.Where(x => x.Name == "Project A")
.Remove().In<Project>().Select(x=>x.Key).ToListAsync();
```
