### ISSUE TITLE
Support for netstandard2.0

### ISSUE THREAD

**Issue by robsiera** [coronabytes/dotnet-arangodb#46]
I needed and created support for netstandard2.0.
I'm willing to share this. 
Maybe you want to create a feature branch to receive my pull request there?

**Comment by coronabytes** [comment]
Hi, can you just lower the 2.1 to 2.0 requirement on the main branch?
I tried this once and just did'nt want to polyfill the WebUtility? thingy...

**Comment by robsiera** [comment]
If you create a branch named netstandard20 I will pull request to that branch. Then you can review what I did. 
It needed minor changes so I went through with it.
You can decide later if you want to keep it, or drop it all. I will not take it as an offense :-)
But if you don't want to bother with it, no problem. Then just reply with Thanks, but no thanks. :-)

**Comment by coronabytes** [comment]
https://github.com/coronabytes/dotnet-arangodb/tree/netstandard2.0

**Comment by robsiera** [comment]
Thx for accepting my PR.
