### ISSUE TITLE
Replacing ArangoViews

### ISSUE THREAD

**Issue by Snotax** [coronabytes/dotnet-arangodb#52]
Hello everybody.

I've done some experiments with the "Create / Drop" View functions and that got me to wonder if there is a "Replace / Update" command implemented somewhere and if not, if that's something that's planned in the future?

Thank you!

**Comment by coronabytes** [comment]
Hi,

All our datasets are so small that dropping and recreating was just easier.
Also (alt least a year ago) to create model differed from the update one.
And then there are 2 apis PUT and PATCH.

I'd glady accept a PR - I don't think it would be to hard.
Maybe try to make a ArangoViewBase class and then inherit and add props in the Create / Update / Patch models as needed

**Comment by coronabytes** [comment]
ok it was easy enough to  do in 5min

**Comment by Snotax** [comment]
@coronabytes You are amazing! Thank you!
