### ISSUE TITLE
Usage of returnNew parameter in Document.CreateAsync

### ISSUE THREAD

**Issue by killerwife** [coronabytes/dotnet-arangodb#61]
As the issue name stands, what is the usecase or the expected syntax for using returnNew parameter in a query like this:

```
var result = await _context.Document.CreateAsync(_options.CurrentValue.DatabaseName, _options.CurrentValue.CollectionNames.Lookaround, lookaround, returnNew: true);
```

The return type is ArangoVoid, does this imply some sort of possiblity to typecast it to an object or parsing the json?

Appreciate any info.

**Comment by coronabytes** [comment]
yes for returnNew / Old you need to use 
Task<ArangoUpdateResult<TR>> CreateAsync<T, TR>

and the parameters are kinda usless on the arangovoid one

**Comment by killerwife** [comment]
I have a silly suggestion, add it to the readme :D Nonetheless, thx for the help, this is what I needed.
