### ISSUE TITLE
3.10 Lacks ComputedValues

### ISSUE THREAD

**Issue by HarryCordewener** [coronabytes/dotnet-arangodb#62]
Would it be possible to push the ComputedValues changes to the 3.10 NuGet so they can be used?

**Comment by coronabytes** [comment]
Hi, 
it wasnt released yet,
try 3.11 und let me know if it works

**Comment by HarryCordewener** [comment]
3.11 NuGet has not been released @coronabytes

**Comment by coronabytes** [comment]
ok, now

**Comment by HarryCordewener** [comment]
Code exists. I will test for functionality.

**Comment by HarryCordewener** [comment]
Yep, it functions. All good to go!
