### ISSUE TITLE
Document creation with db created index

### ISSUE THREAD

**Issue by bbm-design** [coronabytes/dotnet-arangodb#65]
Hello, i wanted to try using padded keys, and relying on the database to generate the key.
but when i try to create a document with no key i get  "arangodb illegal document key".

what's the recommended way to do so.

**Comment by coronabytes** [comment]
Did you look at the following unit test?

```csharp
[Theory]
        [ClassData(typeof(PascalCaseData))]
        public async Task Create(string serializer)
        {
            await SetupAsync(serializer);
            await Arango.Collection.CreateAsync("test", new ArangoCollection
            {
                Name = "test",
                Type = ArangoCollectionType.Document,
                KeyOptions = new ArangoKeyOptions
                {
                    Type = ArangoKeyType.Padded,
                    AllowUserKeys = true
                }
            });

            await Arango.Document.CreateAsync("test", "test", new
            {
                Name = "test"
            });
        }
```

No clue why, however padded keys also require AllowUserKeys = true

**Comment by coronabytes** [comment]
Also take note: You're not allowed to send any _key / id at document creation.
This means Key/Id Properties in your entity model need [JsonIgnore(Default...)]

**Comment by bbm-design** [comment]
switched the key to

```
[JsonIgnore]
public string? Key { get; set; }
```

yet when creating the object like

```
User user = new User()
{
    UserName = "blabla",
    FullName = "full name",
};

await _arango.Document.CreateAsync(transaction, StaticDBIdentifiers.Vertexes.User, user);
```

i still get 

`error : [{"error":true,"errorNum":1221,"errorMessage":"illegal document key"}]`


Object is defined like this
```
if (!await _arango.Collection.ExistAsync(StaticDBIdentifiers.DBName, StaticDBIdentifiers.Vertexes.User))
						{
							await _arango.Collection.CreateAsync(StaticDBIdentifiers.DBName, new ArangoCollection
							{
								Name = StaticDBIdentifiers.Vertexes.User,
								Type = ArangoCollectionType.Document,
								KeyOptions = new ArangoKeyOptions
								{
                                    Type = ArangoKeyType.Padded,
                                    AllowUserKeys = true
                                }
							});
						}
```

**Comment by coronabytes** [comment]
What arangodb version are you using and is it a cluster?

**Comment by bbm-design** [comment]
3.11.1 Community edition, in a single docker container, no clustering, nothing exotic

adding  [System.Text.Json.Serialization.JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] to the key didn't make any change.

i will try adding and object without key, on a manual query, to isolate the issue

**Comment by coronabytes** [comment]
are you sure you're not mixing newtonsoft and system.json.text?

**Comment by bbm-design** [comment]
You are right
i was using newtonsoft 
`config.Serializer = new ArangoNewtonsoftSerializer(new ArangoNewtonsoftCamelCaseContractResolver());`
