### ISSUE TITLE
ArangoIndex Json Deserialization with Inverted Index and Persistant Index

### ISSUE THREAD

**Issue by WGertner** [coronabytes/dotnet-arangodb#69]
Hello, i have been trying to create/init a collection with a couple of indexes. 
When i am trying to read all existing indexes of a collection i am getting a System.Text.Json.JsonException with the Message "The JSON value could not be converted to System.String. Path: $.indexes[1].fields[0]." 
After some research, I found out that there is a difference between the model of the persistent index and the model of the inverted index.

The 'fields' property is a string array in the persistent index and an object array in the inverted index. When querying, however, it tries to convert both to an IList\<string\>

**Comment by coronabytes** [comment]
yeah only newtonsoft works well with ilist

**Comment by vitalii-wowl-work** [comment]
In version 3.11.3 it still appear. And listing the indexes is not possible
