### ISSUE TITLE
Update Document Null Reference Exception

### ISSUE THREAD

**Issue by michel-pi** [coronabytes/dotnet-arangodb#72]
This happens inside this library under huge system load.
Due to the load, no more http requests can be processed.

We receive a `null` value as the result from `SendAsync` or `SendContentAsync`.
This leads to a crash in "ArangoDocumentModule.cs" in "UpdateAsync<T>":

See comment:
```csharp
var res = await UpdateManyAsync<T, ArangoVoid>(database, collection,
	new List<T> { doc }, waitForSync, keepNull, mergeObjects,
	returnOld, returnNew, silent, ignoreRevs, exclusive, cancellationToken).ConfigureAwait(false);

return res.SingleOrDefault(); // res is null!
```

**Comment by coronabytes** [comment]
hmm, maybe your arangodb version does not send an error code on "overload"
it shoud be handled by this.

```csharp
var res = await _httpClient.SendAsync(msg, cancellationToken).ConfigureAwait(false);

if (!res.IsSuccessStatusCode)
    if (throwOnError)
    {
        var errorContent = await res.Content.ReadAsStringAsync().ConfigureAwait(false);
        var error = _configuration.Serializer.Deserialize<ErrorResponse>(errorContent);
        throw new ArangoException(errorContent, error.ErrorMessage,
            (HttpStatusCode) error.Code, (ArangoErrorCode) error.ErrorNum);
    }
    else
    {
        return default;
    }
```

**Comment by michel-pi** [comment]
This is a really odd edge case, not related to the library. It's about limited system resources, socket exhaustion or something alike, which causes undefined behavior.
No need to worry.

We will investigate and i will create PR's as needed
