### ISSUE TITLE
ExecuteAsync failing with: expecting PUT /_api/cursor/<cursor-id>

### ISSUE THREAD

**Issue by CodeCoded** [coronabytes/dotnet-arangodb#9]
Hi,

I'm normally a user of Foxx services, but as a C# dev, so wanted to try your library and see how I get on.

Referenced the open source a few times to work out syntaxes, but think I'm there now to being able to achieve most queries.

Firstly, I wanted to retrieve a list of strings (id's) on ExecuteAsyn but since T must be parameterless constructor type, was unable. Fortunatlely, this mapping was for document _id's so I cast to ArangoHandle. 

But...whilst the ExecuteAsync works fine when limiting the query, it seems to error when the cursor is required with 

```
code: 400
error: true, 
errorMessage: expecting PUT /_api/cursor/<cursor-id>

```
The query generates 200k Ids which I plan to cache in the webserver on startup for fast random lookups of documents.

Can you advise on what I can do to debug this? It's very simple query

`ArangoDb.Query.ExecuteAsync<ArangoHandle>("myDb", $"FOR doc IN coll FILTER doc.myAttr != null RETURN doc._id");
`
 Thanks

**Comment by coronabytes** [comment]
just use
ArangoDb.Query.ExecuteAsync<string>()

ArangoHandle is not for _id
its a database/transaction identifier

**Comment by coronabytes** [comment]
ok, try again with 2.2.3
primitive types weren't allowed,

still the **expecting PUT /_api/cursor/<cursor-id>** sound suspicious

wrote a test with 100k and it ran just fine
